### ISSUE TITLE
an option to choose ace-editor mode

### ISSUE THREAD

**Issue by soonhokong** [leanprover/presentations#2]
example: `#+REVEAL_ACE_EDITOR_THEME: suatomic`

**Comment by leodemoura** [comment]
It would also be useful to have an option to specify the font size in code blocks.

**Comment by soonhokong** [comment]
I think so, I'll add it too.

**Comment by soonhokong** [comment]
Close by https://github.com/soonhokong/org-reveal/commit/da206b54157c279ed05b19a1bf3c0e4f38e943f3

**Comment by soonhokong** [comment]
@leodemoura, 
1. please update the installed `org-reveal` by running `cask update`.
2. then, please add the following lines in your `.org` file:

``` org
#+REVEAL_ACE_THEME: ace/theme/chrome
#+REVEAL_ACE_FONTSIZE: 20px
```

Let me know if you experience a problem.
